# Generated by Django 4.2.30 on 2026-04-14 05:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='open', editable=False, max_length=20)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('referral', 'Referral'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('call', 'Call'), ('email', 'Email'), ('social_media', 'Social media'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='other', max_length=30)),
                ('loss_reason', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_to_project_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ('-created_at',),
                'permissions': [('move_opportunity', 'Can move opportunity between stages'), ('convert_opportunity', 'Can build project seed from won opportunity')],
            },
        ),
        migrations.CreateModel(
            name='OpportunityStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#1E293B', help_text='Hex color used by the kanban UI.', max_length=7)),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_won_stage', models.BooleanField(default=False)),
                ('is_lost_stage', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Opportunity stage',
                'verbose_name_plural': 'Opportunity stages',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OpportunityStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('note', models.TextField(blank=True)),
                ('moved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_opportunity_stages', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries_from', to='sales.opportunitystage')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='sales.opportunity')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries_to', to='sales.opportunitystage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Opportunity stage history',
                'verbose_name_plural': 'Opportunity stage history',
                'ordering': ('-moved_at', '-created_at'),
                'get_latest_by': 'moved_at',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='sales.opportunitystage'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['status', 'stage'], name='sales_oppor_status_7b53d0_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['client', 'status'], name='sales_oppor_client__e9dc45_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['responsible', 'status'], name='sales_oppor_respons_7636da_idx'),
        ),
    ]
