# Generated by Django 4.2.30 on 2026-04-27 01:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('title', models.CharField(max_length=180)),
                ('invoice_number', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('issued_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_receivable', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Account receivable',
                'verbose_name_plural': 'Accounts receivable',
                'ordering': ['-issued_date', '-created_at'],
                'permissions': [('register_payment', 'Can register payment'), ('view_pending_accounts', 'Can view pending accounts'), ('cancel_account_receivable', 'Can cancel account receivable')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank transfer'), ('credit_card', 'Credit card'), ('debit_card', 'Debit card'), ('zelle', 'Zelle'), ('other', 'Other')], default='cash', max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.accountreceivable')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', Decimal('0.01'))), name='billing_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='accountreceivable',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', Decimal('0.01'))), name='billing_account_total_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='accountreceivable',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__gte', Decimal('0.00'))), name='billing_account_amount_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='accountreceivable',
            constraint=models.CheckConstraint(check=models.Q(('balance_due__gte', Decimal('0.00'))), name='billing_account_balance_due_non_negative'),
        ),
    ]
