# Generated by Django 4.2.30 on 2026-04-22 03:14

import apps.media_assets.models.entities
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('image', models.ImageField(upload_to=apps.media_assets.models.entities.project_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('classification', models.CharField(choices=[('before', 'Before'), ('in_progress', 'In progress'), ('final', 'Final')], default='in_progress', max_length=20)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'ordering': ('-taken_at', '-created_at'),
                'permissions': (('view_project_gallery', 'Can view project gallery'), ('upload_projectphoto', 'Can upload project photos'), ('replace_projectphoto', 'Can replace project photos')),
            },
        ),
    ]
