DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
MAX_UPLOAD_SIZE_MB = 10

SAFE_HTTP_METHODS = {"GET", "HEAD", "OPTIONS", "TRACE"}

VISIT_REMINDER_LOOKAHEAD_HOURS = 24
ACTIVITY_LOGGER_NAME = "crm.activity"
NOTIFICATION_LOGGER_NAME = "crm.notifications"