# Generated by Django 4.2.30 on 2026-04-09 04:16

import apps.users.models.entities
import core.validators
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electronico')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone_number], verbose_name='telefono')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='cargo')),
                ('must_change_password', models.BooleanField(default=False, help_text='Obligar al usuario a cambiar su contraseña en el próximo inicio de sesión', verbose_name='debe cambiar contraseña')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ('username',),
            },
            managers=[
                ('objects', apps.users.models.entities.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('identifier_used', models.CharField(blank=True, help_text='Email o username usado en el intento', max_length=255, verbose_name='identificador usado')),
                ('event_type', models.CharField(choices=[('login_success', 'Login exitoso'), ('login_failed', 'Login fallido'), ('logout', 'Logout'), ('password_reset_request', 'Solicitud de recuperacion'), ('password_reset_complete', 'Recuperacion completada'), ('access_denied', 'Acceso denegado')], db_index=True, max_length=50, verbose_name='tipo de evento')),
                ('event_status', models.CharField(db_index=True, default='success', max_length=20, verbose_name='estado del evento')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='direccion IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Request ID')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalles adicionales')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'log de acceso',
                'verbose_name_plural': 'logs de acceso',
                'db_table': 'user_access_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_access_user_id_167a50_idx'), models.Index(fields=['event_type', '-created_at'], name='user_access_event_t_ccd9bc_idx'), models.Index(fields=['ip_address'], name='user_access_ip_addr_6037e0_idx')],
            },
        ),
    ]
