# Generated by Django 4.2.30 on 2026-04-10 04:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('legal_name', models.CharField(db_index=True, max_length=255, verbose_name='razón social / nombre completo')),
                ('commercial_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='nombre comercial')),
                ('client_type', models.CharField(choices=[('company', 'Empresa'), ('individual', 'Persona natural')], db_index=True, default='company', max_length=20, verbose_name='tipo de cliente')),
                ('document_number', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='documento / RUC')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='teléfono principal')),
                ('alternate_phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono alterno')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ciudad')),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='provincia / estado')),
                ('country', models.CharField(blank=True, default='Ecuador', max_length=120, verbose_name='país')),
                ('notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('lead', 'Prospecto')], db_index=True, default='active', max_length=20, verbose_name='estado')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='activo')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='desactivado el')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_clients', to=settings.AUTH_USER_MODEL, verbose_name='desactivado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('legal_name', 'commercial_name'),
                'permissions': (('deactivate_client', 'Can deactivate client'), ('reactivate_client', 'Can reactivate client')),
            },
        ),
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='actualizado en')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('interaction_type', models.CharField(choices=[('call', 'Llamada'), ('email', 'Correo'), ('whatsapp', 'WhatsApp'), ('meeting', 'Reunión'), ('visit', 'Visita'), ('note', 'Nota'), ('other', 'Otro')], db_index=True, max_length=20, verbose_name='tipo de interacción')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha de interacción')),
                ('summary', models.CharField(max_length=255, verbose_name='resumen')),
                ('description', models.TextField(blank=True, verbose_name='detalle')),
                ('follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='seguimiento programado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='eliminado por')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_client_interactions', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'interacción de cliente',
                'verbose_name_plural': 'interacciones de clientes',
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
    ]
