# Generated by Django 4.2.30 on 2026-04-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitreminderlog',
            options={},
        ),
        migrations.AddField(
            model_name='visitreminderlog',
            name='execution_date',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha lógica de ejecución usada para evitar recordatorios duplicados.', null=True),
        ),
        migrations.AlterField(
            model_name='technicalvisit',
            name='reminder_type',
            field=models.CharField(choices=[('day_before', 'One day before'), ('same_day', 'Same day'), ('two_hours_before', 'Two hours before')], default='day_before', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitreminderlog',
            name='reminder_type',
            field=models.CharField(choices=[('day_before', 'One day before'), ('same_day', 'Same day'), ('two_hours_before', 'Two hours before')], max_length=20),
        ),
    ]
